name: Delete merged branch

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Delete branch
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo
            const branch = context.payload.pull_request.head.ref
            console.log(`Deleting ${branch}...`)
            await github.git.deleteRef({
              owner,
              repo,
              ref: 'heads/' + branch
            })
